using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Unity.VisualScripting;
using UnityEngine;
using Assets.Script;
using BOTF3D_Core;
using BOTF3D_Combat;
using UnityEngine.XR;
using JetBrains.Annotations;

namespace BOTF3D_GalaxyMap
{
    [System.Serializable]
	public class StarSystem
	{
        #region Fields

        public int _systemInt;
        //public StarSystemEnum _sysEnum;
        public string _sysName;
        public StarType _starType;
        //public Civ _civEnum;
       // public Sprite _civInsignia;// do we get it from Civ and not system??
        public Civilization _ownerCiv;
       // public string _ownerName;
        public int _systemPopulation;
        //public float _systemResearch;
        //private readonly Treasury _treasury;
        //private int _maintenanceCostLastTurn;
        //private int _rankCredits;
        //public List<CivHistory> _civHist_List = new List<CivHistory>();
        public bool _homeColony;
        public string _text;
        #endregion Fields

        //[SerializeField]
        //public static List<StarSystem> StarSystemList;
        //public static Dictionary<int, StarSystem> StarSystemDictionary;

        #region StarSystem
        //private StarSystem SOL;
        //private StarSystem ROMULUS;
        //private StarSystem KRONOS;
        //private StarSystem CARDASSIA;
        //private StarSystem OMARIAN_NEBULA;
        //private StarSystem UNICOMPLEX;

        //private StarSystem ACAMA;
        //private StarSystem AKAALI;
        //private StarSystem AKRITIRI;
        //private StarSystem ALDEA;
        //private StarSystem ALGOL;
        //private StarSystem ALSAURI;
        //private StarSystem ANDORI;
        //private StarSystem ANGOSIA;

        //#region More StarSystems
        ////private StarSystem ANKARI;
        ////private StarSystem ANTEDEA;
        ////private StarSystem ANTICA;
        ////private StarSystem ARBAZ;
        ////private StarSystem ARDANA;
        ////private StarSystem ARGRATHI;
        ////private StarSystem ARKARI;
        ////private StarSystem ATREA;
        ////private StarSystem AXANAR;
        ////private StarSystem BAJOR;
        ////private StarSystem BAKU;
        ////private StarSystem BANDI;
        ////private StarSystem BANEA;
        ////private StarSystem BARZA;
        ////private StarSystem BENZAR;
        ////private StarSystem BETAZED;
        ////private StarSystem BILANA;
        ////private StarSystem BOLIA;
        ////private StarSystem BOMAR;
        ////private StarSystem BOSLIC;
        ////private StarSystem BOTHA;
        ////private StarSystem BREEL;
        ////private StarSystem BREEN;
        ////private StarSystem BREKKA;
        ////private StarSystem BYNAR;
        ////private StarSystem CAIRN;
        ////private StarSystem CALDON;
        ////private StarSystem CAPELLA;
        ////private StarSystem CHALNOTH;
        ////private StarSystem CORIDAN;
        ////private StarSystem CORVALLE;
        ////private StarSystem CYTHERIA;
        ////private StarSystem DELTA;
        ////private StarSystem DENOBULA;
        ////private StarSystem DEVORE;
        ////private StarSystem DOPTERIA;
        ////private StarSystem DOSI;
        ////private StarSystem DRAI;
        ////private StarSystem DREMA;
        ////private StarSystem EDO;
        ////private StarSystem ELAURIA;
        ////private StarSystem ELAYSIA;
        ////private StarSystem ENTHARA;
        ////private StarSystem EVORA;
        ////private StarSystem EXCALBIA;
        ////private StarSystem FERENGI;
        ////private StarSystem FLAXIA;
        ////private StarSystem GORN;
        ////private StarSystem GRAZERITES;
        ////private StarSystem HAAKONIA;
        ////private StarSystem HALKA;
        ////private StarSystem HAZARI;
        ////private StarSystem HEKARA;
        ////private StarSystem HIROGEN;
        ////private StarSystem HORTA;
        ////private StarSystem IYAARA;
        ////private StarSystem JNAII;
        ////private StarSystem KAELON;
        ////private StarSystem KAREMMA;
        ////private StarSystem KAZON;
        ////private StarSystem KELLERUN;
        ////private StarSystem KESPRYTT;
        ////private StarSystem KLAESTRON;
        ////private StarSystem KRADIN;
        ////private StarSystem KREETASSA;
        ////private StarSystem KRIOSIA;
        ////private StarSystem KTARIA;
        ////private StarSystem LEDOSIA;
        ////private StarSystem LISSEPIA;
        ////private StarSystem LOKIRRIM;
        ////private StarSystem LURIA;
        ////private StarSystem MALCORIA;
        ////private StarSystem MALON;
        ////private StarSystem MAQUIS;
        ////private StarSystem MARKALIA;
        ////private StarSystem MERIDIA;
        ////private StarSystem MINTAKA;
        ////private StarSystem MIRADORN;
        ////private StarSystem MIZARIA;
        ////private StarSystem MOKRA;
        ////private StarSystem MONEA;
        ////private StarSystem NAUSICAA;
        ////private StarSystem NECHANI;
        ////private StarSystem NEZU;
        ////private StarSystem NORCADIA;
        ////private StarSystem NUMIRI;
        ////private StarSystem NUUBARI;
        ////private StarSystem NYRIA;
        ////private StarSystem OCAMPA;
        ////private StarSystem ORION;
        ////private StarSystem ORNARA;
        ////private StarSystem PAKLED;
        ////private StarSystem PARADA;
        ////private StarSystem QUARREN;
        ////private StarSystem RAKHARI;
        ////private StarSystem RAKOSA;
        ////private StarSystem RAMATIA;
        ////private StarSystem REMUS;
        ////private StarSystem RIGELIA;
        ////private StarSystem RISIA;
        ////private StarSystem RUTIA;
        ////private StarSystem SELAY;
        ////private StarSystem SHELIAK;
        ////private StarSystem SIKARIA;
        ////private StarSystem SKRREEA;
        ////private StarSystem SONA;
        ////private StarSystem SULIBAN;
        ////private StarSystem TAKARA;
        ////private StarSystem TAKARIA;
        ////private StarSystem TAKTAK;
        ////private StarSystem TALARIA;
        ////private StarSystem TALAX;
        ////private StarSystem TALOSIA;
        ////private StarSystem TAMARIA;
        ////private StarSystem TANUGA;
        ////private StarSystem TELLAR;
        ////private StarSystem TEPLA;
        ////private StarSystem THOLIA;
        ////private StarSystem TILONIA;
        ////private StarSystem TLANI;
        ////private StarSystem TRABE;
        ////private StarSystem TRILL;
        ////private StarSystem TROGORA;
        ////private StarSystem TZENKETHI;
        ////private StarSystem ULLIA;
        ////private StarSystem VAADWAUR;
        ////private StarSystem VENTAXIA;
        ////private StarSystem VHNORI;
        ////private StarSystem VIDIIA;
        ////private StarSystem VISSIA;
        ////private StarSystem VORGON;
        ////private StarSystem VORI;
        ////private StarSystem _40_ERIDANI_A_II;
        ////private StarSystem WADI;
        ////private StarSystem XANTHAN;
        ////private StarSystem XEPOLITES;
        ////private StarSystem XINDI;
        ////private StarSystem XYRILLIA;
        ////private StarSystem YADERA;
        ////private StarSystem YRIDIA;
        ////private StarSystem ZAHL;
        ////private StarSystem ZAKDORN;
        ////private StarSystem ZALKONIA;
        ////private StarSystem ZIBAL;
        //#endregion
        #endregion
        public StarSystem(int sysInt)
        {
            this._systemInt = sysInt;           
        }
        //public StarSystem(int systemInt, StarType starType, Civ civ)
        //{
        //    //_gameManager = GameManager.Instance;
        //    _systemInt = systemInt;
        //    //_sysEnum = (StarSystemEnum)systemInt;
        //    //_sysName = _sysEnum.ToString();
        //    _starType = starType;
        //    _civEnum = civ;
        //    //_civInsignia leave for StarSystemDataBase to do
        //    //_ownerCiv = Civilization(civ); // whait for StarSystemDataBase to do
        //    _ownerName = civ.ToString();
        //    _systemPopulation = 2;
        //    _systemResearch = 2;
        //    _homeColony = true;
        //    _text = "blah, blah, blah";
        //}

        private void Awake()
        {
            ////_gameManager = GameManager.Instance;
            //StarSystem SOL = new StarSystem();
            //StarSystem ROMULUS = new StarSystem();
            //StarSystem KRONOS = new StarSystem();
            //StarSystem CARDASSIA = new StarSystem();
            //StarSystem OMARIAN_NEBULA = new StarSystem();
            //StarSystem UNICOMPLEX = new StarSystem();
            //StarSystem ACAMA = new StarSystem();

            //StarSystem AKAALI = new StarSystem();
            //StarSystem AKRITIRI = new StarSystem();
            //StarSystem ALDEA = new StarSystem();
            //StarSystem ALGOL = new StarSystem();
            //StarSystem ALSAURI = new StarSystem();
            //StarSystem ANDORI = new StarSystem();
            //StarSystem ANGOSIA = new StarSystem();
            #region more systems
            ////ANKARI = new StarSystem();
            ////ANTEDEA = new StarSystem();
            ////ANTICA = new StarSystem();
            ////ARBAZ = new StarSystem();
            ////ARDANA = new StarSystem();
            ////ARGRATHI = new StarSystem();
            ////ARKARI = new StarSystem();
            ////ATREA = new StarSystem();
            ////AXANAR = new StarSystem();
            ////BAJOR = new StarSystem();
            ////BAKU = new StarSystem();
            ////BANDI = new StarSystem();
            ////BANEA = new StarSystem();
            ////BARZA = new StarSystem();
            ////BENZAR = new StarSystem();
            ////BETAZED = new StarSystem();
            ////BILANA = new StarSystem();
            ////BOLIA = new StarSystem();
            ////BOMAR = new StarSystem();
            ////BOSLIC = new StarSystem();
            ////BOTHA = new StarSystem();
            ////BREEL = new StarSystem();
            ////BREEN = new StarSystem();
            ////BREKKA = new StarSystem();
            ////BYNAR = new StarSystem();
            ////CAIRN = new StarSystem();
            ////CALDON = new StarSystem();
            ////CAPELLA = new StarSystem();
            ////CHALNOTH = new StarSystem();
            ////CORIDAN = new StarSystem();
            ////CORVALLE = new StarSystem();
            ////CYTHERIA = new StarSystem();
            ////DELTA = new StarSystem();
            ////DENOBULA = new StarSystem();
            ////DEVORE = new StarSystem();
            ////DOPTERIA = new StarSystem();
            ////DOSI = new StarSystem();
            ////DRAI = new StarSystem();
            ////DREMA = new StarSystem();
            ////EDO = new StarSystem();
            ////ELAURIA = new StarSystem();
            ////ELAYSIA = new StarSystem();
            ////ENTHARA = new StarSystem();
            ////EVORA = new StarSystem();
            ////EXCALBIA = new StarSystem();
            ////FERENGI = new StarSystem();
            ////FLAXIA = new StarSystem();
            ////GORN = new StarSystem();
            ////GRAZERITES = new StarSystem();
            ////HAAKONIA = new StarSystem();
            ////HALKA = new StarSystem();
            ////HAZARI = new StarSystem();
            ////HEKARA = new StarSystem();
            ////HIROGEN = new StarSystem();
            ////HORTA = new StarSystem();
            ////IYAARA = new StarSystem();
            ////JNAII = new StarSystem();
            ////KAELON = new StarSystem();
            ////KAREMMA = new StarSystem();
            ////KAZON = new StarSystem();
            ////KELLERUN = new StarSystem();
            ////KESPRYTT = new StarSystem();
            ////KLAESTRON = new StarSystem();
            ////KRADIN = new StarSystem();
            ////KREETASSA = new StarSystem();
            ////KRIOSIA = new StarSystem();
            ////KTARIA = new StarSystem();
            ////LEDOSIA = new StarSystem();
            ////LISSEPIA = new StarSystem();
            ////LOKIRRIM = new StarSystem();
            ////LURIA = new StarSystem();
            ////MALCORIA = new StarSystem();
            ////MALON = new StarSystem();
            ////MAQUIS = new StarSystem();
            ////MARKALIA = new StarSystem();
            ////MERIDIA = new StarSystem();
            ////MINTAKA = new StarSystem();
            ////MIRADORN = new StarSystem();
            ////MIZARIA = new StarSystem();
            ////MOKRA = new StarSystem();
            ////MONEA = new StarSystem();
            ////NAUSICAA = new StarSystem();
            ////NECHANI = new StarSystem();
            ////NEZU = new StarSystem();
            ////NORCADIA = new StarSystem();
            ////NUMIRI = new StarSystem();
            ////NUUBARI = new StarSystem();
            ////NYRIA = new StarSystem();
            ////OCAMPA = new StarSystem();
            ////ORION = new StarSystem();
            ////ORNARA = new StarSystem();
            ////PAKLED = new StarSystem();
            ////PARADA = new StarSystem();
            ////QUARREN = new StarSystem();
            ////RAKHARI = new StarSystem();
            ////RAKOSA = new StarSystem();
            ////RAMATIA = new StarSystem();
            ////REMUS = new StarSystem();
            ////RIGELIA = new StarSystem();
            ////RISIA = new StarSystem();
            ////RUTIA = new StarSystem();
            ////SELAY = new StarSystem();
            ////SHELIAK = new StarSystem();
            ////SIKARIA = new StarSystem();
            ////SKRREEA = new StarSystem();
            ////SONA = new StarSystem();
            ////SULIBAN = new StarSystem();
            ////TAKARA = new StarSystem();
            ////TAKARIA = new StarSystem();
            ////TAKTAK = new StarSystem();
            ////TALARIA = new StarSystem();
            ////TALAX = new StarSystem();
            ////TALOSIA = new StarSystem();
            ////TAMARIA = new StarSystem();
            ////TANUGA = new StarSystem();
            ////TELLAR = new StarSystem();
            ////TEPLA = new StarSystem();
            ////THOLIA = new StarSystem();
            ////TILONIA = new StarSystem();
            ////TLANI = new StarSystem();
            ////TRABE = new StarSystem();
            ////TRILL = new StarSystem();
            ////TROGORA = new StarSystem();
            ////TZENKETHI = new StarSystem();
            ////ULLIA = new StarSystem();
            ////VAADWAUR = new StarSystem();
            ////VENTAXIA = new StarSystem();
            ////VHNORI = new StarSystem();
            ////VIDIIA = new StarSystem();
            ////VISSIA = new StarSystem();
            ////VORGON = new StarSystem();
            ////VORI = new StarSystem();
            ////_40_ERIDANI_A_II = new StarSystem();
            ////WADI = new StarSystem();
            ////XANTHAN = new StarSystem();
            ////XEPOLITES = new StarSystem();
            ////XINDI = new StarSystem();
            ////XYRILLIA = new StarSystem();
            ////YADERA = new StarSystem();
            ////YRIDIA = new StarSystem();
            ////ZAHL = new StarSystem();
            ////ZAKDORN = new StarSystem();
            ////ZALKONIA = new StarSystem();
            ////ZIBAL = new StarSystem();
            #endregion end more system

            #region Build List
            //List<StarSystem> _sysListInstance = new List<StarSystem>();
            //_sysListInstance.Add(SOL);
            //_sysListInstance.Add(ROMULUS);
            //_sysListInstance.Add(KRONOS);
            //_sysListInstance.Add(CARDASSIA);
            //_sysListInstance.Add(OMARIAN_NEBULA);
            //_sysListInstance.Add(UNICOMPLEX);

            //_sysListInstance.Add(ACAMA);
            //_sysListInstance.Add(AKAALI);
            //_sysListInstance.Add(AKRITIRI);
            //_sysListInstance.Add(ALDEA);
            //_sysListInstance.Add(ALGOL);
            //_sysListInstance.Add(ALSAURI);
            //_sysListInstance.Add(ANDORI);
            //_sysListInstance.Add(ANGOSIA);
            #region Build More List
            ////_sysListInstance.Add(ANKARI);
            ////_sysListInstance.Add(ANTEDEA);
            ////_sysListInstance.Add(ANTICA);
            ////_sysListInstance.Add(ARBAZ);
            ////_sysListInstance.Add(ARDANA);
            ////_sysListInstance.Add(ARGRATHI);
            ////_sysListInstance.Add(ARKARI);
            ////_sysListInstance.Add(ATREA);
            ////_sysListInstance.Add(AXANAR);
            ////_sysListInstance.Add(BAJOR);
            ////_sysListInstance.Add(BAKU);
            ////_sysListInstance.Add(BANDI);
            ////_sysListInstance.Add(BANEA);
            ////_sysListInstance.Add(BARZA);
            ////_sysListInstance.Add(BENZAR);
            ////_sysListInstance.Add(BETAZED);
            ////_sysListInstance.Add(BILANA);
            ////_sysListInstance.Add(BOLIA);
            ////_sysListInstance.Add(BOMAR);
            ////_sysListInstance.Add(BOSLIC);
            ////_sysListInstance.Add(BOTHA);
            ////_sysListInstance.Add(BREEL);
            ////_sysListInstance.Add(BREEN);
            ////_sysListInstance.Add(BREKKA);
            ////_sysListInstance.Add(BYNAR);
            ////_sysListInstance.Add(CAIRN);
            ////_sysListInstance.Add(CALDON);
            ////_sysListInstance.Add(CAPELLA);
            ////_sysListInstance.Add(CHALNOTH);
            ////_sysListInstance.Add(CORIDAN);
            ////_sysListInstance.Add(CORVALLE);
            ////_sysListInstance.Add(CYTHERIA);
            ////_sysListInstance.Add(DELTA);
            ////_sysListInstance.Add(DENOBULA);
            ////_sysListInstance.Add(DEVORE);
            ////_sysListInstance.Add(DOPTERIA);
            ////_sysListInstance.Add(DOSI);
            ////_sysListInstance.Add(DRAI);
            ////_sysListInstance.Add(DREMA);
            ////_sysListInstance.Add(EDO);
            ////_sysListInstance.Add(ELAURIA);
            ////_sysListInstance.Add(ELAYSIA);
            ////_sysListInstance.Add(ENTHARA);
            ////_sysListInstance.Add(EVORA);
            ////_sysListInstance.Add(EXCALBIA);
            ////_sysListInstance.Add(FERENGI);
            ////_sysListInstance.Add(FLAXIA);
            ////_sysListInstance.Add(GORN);
            ////_sysListInstance.Add(GRAZERITES);
            ////_sysListInstance.Add(HAAKONIA);
            ////_sysListInstance.Add(HALKA);
            ////_sysListInstance.Add(HAZARI);
            ////_sysListInstance.Add(HEKARA);
            ////_sysListInstance.Add(HIROGEN);
            ////_sysListInstance.Add(HORTA);
            ////_sysListInstance.Add(IYAARA);
            ////_sysListInstance.Add(JNAII);
            ////_sysListInstance.Add(KAELON);
            ////_sysListInstance.Add(KAREMMA);
            ////_sysListInstance.Add(KAZON);
            ////_sysListInstance.Add(KELLERUN);
            ////_sysListInstance.Add(KESPRYTT);
            ////_sysListInstance.Add(KLAESTRON);
            ////_sysListInstance.Add(KRADIN);
            ////_sysListInstance.Add(KREETASSA);
            ////_sysListInstance.Add(KRIOSIA);
            ////_sysListInstance.Add(KTARIA);
            ////_sysListInstance.Add(LEDOSIA);
            ////_sysListInstance.Add(LISSEPIA);
            ////_sysListInstance.Add(LOKIRRIM);
            ////_sysListInstance.Add(LURIA);
            ////_sysListInstance.Add(MALCORIA);
            ////_sysListInstance.Add(MALON);
            ////_sysListInstance.Add(MAQUIS);
            ////_sysListInstance.Add(MARKALIA);
            ////_sysListInstance.Add(MERIDIA);
            ////_sysListInstance.Add(MINTAKA);
            ////_sysListInstance.Add(MIRADORN);
            ////_sysListInstance.Add(MIZARIA);
            ////_sysListInstance.Add(MOKRA);
            ////_sysListInstance.Add(MONEA);
            ////_sysListInstance.Add(NAUSICAA);
            ////_sysListInstance.Add(NECHANI);
            ////_sysListInstance.Add(NEZU);
            ////_sysListInstance.Add(NORCADIA);
            ////_sysListInstance.Add(NUMIRI);
            ////_sysListInstance.Add(NUUBARI);
            ////_sysListInstance.Add(NYRIA);
            ////_sysListInstance.Add(OCAMPA);
            ////_sysListInstance.Add(ORION);
            ////_sysListInstance.Add(ORNARA);
            ////_sysListInstance.Add(PAKLED);
            ////_sysListInstance.Add(PARADA);
            ////_sysListInstance.Add(QUARREN);
            ////_sysListInstance.Add(RAKHARI);
            ////_sysListInstance.Add(RAKOSA);
            ////_sysListInstance.Add(RAMATIA);
            ////_sysListInstance.Add(REMUS);
            ////_sysListInstance.Add(RIGELIA);
            ////_sysListInstance.Add(RISIA);
            ////_sysListInstance.Add(RUTIA);
            ////_sysListInstance.Add(SELAY);
            ////_sysListInstance.Add(SHELIAK);
            ////_sysListInstance.Add(SIKARIA);
            ////_sysListInstance.Add(SKRREEA);
            ////_sysListInstance.Add(SONA);
            ////_sysListInstance.Add(SULIBAN);
            ////_sysListInstance.Add(TAKARA);
            ////_sysListInstance.Add(TAKARIA);
            ////_sysListInstance.Add(TAKTAK);
            ////_sysListInstance.Add(TALARIA);
            ////_sysListInstance.Add(TALAX);
            ////_sysListInstance.Add(TALOSIA);
            ////_sysListInstance.Add(TAMARIA);
            ////_sysListInstance.Add(TANUGA);
            ////_sysListInstance.Add(TELLAR);
            ////_sysListInstance.Add(TEPLA);
            ////_sysListInstance.Add(THOLIA);
            ////_sysListInstance.Add(TILONIA);
            ////_sysListInstance.Add(TLANI);
            ////_sysListInstance.Add(TRABE);
            ////_sysListInstance.Add(TRILL);
            ////_sysListInstance.Add(TROGORA);
            ////_sysListInstance.Add(TZENKETHI);
            ////_sysListInstance.Add(ULLIA);
            ////_sysListInstance.Add(VAADWAUR);
            ////_sysListInstance.Add(VENTAXIA);
            ////_sysListInstance.Add(VHNORI);
            ////_sysListInstance.Add(VIDIIA);
            ////_sysListInstance.Add(VISSIA);
            ////_sysListInstance.Add(VORGON);
            ////_sysListInstance.Add(VORI);
            ////_sysListInstance.Add(_40_ERIDANI_A_II);
            ////_sysListInstance.Add(WADI);
            ////_sysListInstance.Add(XANTHAN);
            ////_sysListInstance.Add(XEPOLITES);
            ////_sysListInstance.Add(XINDI);
            ////_sysListInstance.Add(XYRILLIA);
            ////_sysListInstance.Add(YADERA);
            ////_sysListInstance.Add(YRIDIA);
            ////_sysListInstance.Add(ZAHL);
            ////_sysListInstance.Add(ZAKDORN);
            ////_sysListInstance.Add(ZALKONIA);
            ////_sysListInstance.Add(ZIBAL);
            #endregion
            #endregion
            //////hoverTipManager.TransferSystemList(_sysListInstance.ToArray());
            //StarSystemList = _sysListInstance; // static list, single instances of all systems.
            //for (int i = 0; i < StarSystemList.Count; i++)
            //{
            //    // Fix me
            //    //StarSystemDictionary.Add((int)(StarSystemEnum)i, StarSystemList[i]); // hope this keep starsystem int values if some civs are not used
            //}
        }
        //public static StarSystem Create(int systemInt, string[] stings)
        //{
        //    StarSystem daSystem = StarSystemDictionary[systemInt];
        //    daSystem._systemInt = systemInt;
        //    daSystem._sysEnum = (StarSystemEnum)systemInt;
        //    daSystem._sysName = stings[4];
        //    StarType star;
        //    if (Enum.TryParse(stings[7], out star))
        //        daSystem._starType = star;
        //    daSystem._ownerCiv = Civilization.Create(systemInt);
        //    //daSystem._ownerName = daSystem._ownerCiv.name;
        //    //_civInsignia leave for StarSystemDataBase to do
        //    //    _systemPopulation = 2;
        //    //    _systemResearch = 2;
        //    //    _homeColony = true;
        //    //    _text = "blah, blah, blah";
        //    return daSystem;
        //}
    }
}
